# Generated by Django 4.2 on 2023-04-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='trainability',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
